"""
core/page_builder.py
--------------------
Takes one page's HTML and rewrites it for static local display:

  1. All asset src/href → local relative paths
  2. Internal page links → rewritten to local .html paths
  3. <form> actions → neutralised (no data submission)
  4. Tracking scripts stripped
  5. <base> tag removed
  6. Static clone banner injected
"""

import re
from urllib.parse import urljoin, urlparse, urldefrag

from bs4 import BeautifulSoup, Comment
from utils.logger import setup_logger

log = setup_logger("builder")

_BACKEND_RE = re.compile(
    r'(login|logout|signin|signup|register|/auth|oauth|/api/|/api$|admin)',
    re.I
)
_TRACKING_RE = re.compile(
    r'(google-analytics|googletagmanager|facebook\.net|fbevents|'
    r'hotjar|doubleclick|segment\.com|mixpanel|amplitude|intercom|'
    r'drift\.com|zendesk|recaptcha|clarity\.ms)',
    re.I
)

_BANNER = (
    "\n  STATIC CLONE — generated by WebCloner\n"
    "  Visual snapshot only. No backend functionality.\n"
)


class PageBuilder:
    """
    Rewrites one page's HTML for offline static browsing.

    Parameters
    ----------
    html           : fetched HTML string
    page_url       : original URL of this page
    site_origin    : scheme + domain  (e.g. "https://www.example.com")
    asset_map      : { original_url -> local_rel_path }  (from AssetHandler)
    stylesheet_map : { original_href -> local_rel_path } (from CSSExtractor)
    url_to_local   : { page_url -> local_html_path }     (built by SiteCloner)
    inline_css     : if True, embed combined CSS instead of linking
    combined_css   : all CSS text (used when inline_css=True)
    """

    def __init__(
        self,
        html: str,
        page_url: str,
        site_origin: str,
        asset_map: dict,
        stylesheet_map: dict,
        url_to_local: dict,
        inline_css: bool = False,
        combined_css: str = "",
    ):
        self.html           = html
        self.page_url       = page_url
        self.site_origin    = site_origin
        self.asset_map      = asset_map
        self.stylesheet_map = stylesheet_map
        self.url_to_local   = url_to_local
        self.inline_css     = inline_css
        self.combined_css   = combined_css

    def build(self) -> str:
        soup = BeautifulSoup(self.html, "html.parser")

        self._inject_banner(soup)
        self._fix_base_tag(soup)
        self._rewrite_stylesheets(soup)
        self._rewrite_images(soup)
        self._rewrite_scripts(soup)
        self._rewrite_internal_links(soup)
        self._neutralise_forms(soup)

        if self.inline_css:
            self._inline_all_css(soup)

        return str(soup)

    # ── rewriters ───────────────────────────────────────────────────────────

    def _rewrite_stylesheets(self, soup):
        for tag in soup.find_all("link"):
            rel = " ".join(tag.get("rel", []))
            if "stylesheet" not in rel:
                continue
            href = tag.get("href", "")
            abs_href = urljoin(self.page_url, href)
            local = self.stylesheet_map.get(href) or self.stylesheet_map.get(abs_href)
            if local:
                tag["href"] = local

    def _rewrite_images(self, soup):
        # <img>
        for tag in soup.find_all("img"):
            if tag.get("src"):
                local = self._resolve(tag["src"])
                if local:
                    tag["src"] = local
            if tag.get("srcset"):
                tag["srcset"] = self._rewrite_srcset(tag["srcset"])

        # <source>
        for tag in soup.find_all("source"):
            if tag.get("src"):
                local = self._resolve(tag["src"])
                if local:
                    tag["src"] = local
            if tag.get("srcset"):
                tag["srcset"] = self._rewrite_srcset(tag["srcset"])

        # <link rel=icon>
        for tag in soup.find_all("link"):
            rel = " ".join(tag.get("rel", []))
            if any(r in rel for r in ("icon", "apple-touch", "mask-icon")):
                href = tag.get("href", "")
                local = self._resolve(href)
                if local:
                    tag["href"] = local

        # Inline style url()
        for tag in soup.find_all(style=True):
            tag["style"] = self._rewrite_css_urls(tag["style"])

    def _rewrite_scripts(self, soup):
        kept = removed = 0
        for tag in soup.find_all("script"):
            src = tag.get("src", "")
            if src and _TRACKING_RE.search(src):
                tag.decompose()
                removed += 1
                continue
            if src:
                local = self._resolve(src)
                if local:
                    tag["src"] = local
            kept += 1
        if removed:
            log.debug(f"  Stripped {removed} tracking script(s)")

    def _rewrite_internal_links(self, soup):
        """Rewrite <a href> internal links to point to local .html files."""
        for tag in soup.find_all("a", href=True):
            href = tag["href"].strip()
            if not href or href.startswith(("mailto:", "tel:", "javascript:", "#")):
                continue

            abs_url, _ = urldefrag(urljoin(self.page_url, href))
            parsed = urlparse(abs_url)

            # Is it a backend/auth link?
            if _BACKEND_RE.search(abs_url):
                tag["href"] = "#"
                continue

            # Is it an internal page we've crawled?
            if abs_url in self.url_to_local:
                tag["href"] = self.url_to_local[abs_url]
                continue

            # Is it internal but not crawled (e.g. over page limit)?
            if parsed.netloc == urlparse(self.site_origin).netloc:
                # Keep as absolute so it still works if user is online
                tag["href"] = abs_url

    def _neutralise_forms(self, soup):
        count = 0
        for form in soup.find_all("form"):
            form["action"]   = "#"
            form["onsubmit"] = "return false;"
            count += 1
        if count:
            log.debug(f"  Neutralised {count} form(s)")

    def _fix_base_tag(self, soup):
        for base in soup.find_all("base"):
            base.decompose()

    def _inject_banner(self, soup):
        if soup.html:
            soup.html.insert(0, Comment(_BANNER))

    def _inline_all_css(self, soup):
        for tag in soup.find_all("link", rel=lambda r: r and "stylesheet" in r):
            tag.decompose()
        style = soup.new_tag("style")
        style.string = self.combined_css
        head = soup.find("head") or soup
        head.append(style)

    # ── helpers ─────────────────────────────────────────────────────────────

    def _resolve(self, raw: str) -> str | None:
        if not raw or raw.startswith("data:"):
            return None
        abs_url = urljoin(self.page_url, raw)
        return self.asset_map.get(raw) or self.asset_map.get(abs_url)

    def _rewrite_srcset(self, srcset: str) -> str:
        parts = []
        for part in srcset.split(","):
            segs = part.strip().split()
            if not segs:
                continue
            local = self._resolve(segs[0]) or segs[0]
            parts.append(f"{local} {' '.join(segs[1:])}".strip())
        return ", ".join(parts)

    def _rewrite_css_urls(self, style: str) -> str:
        def _rep(m):
            raw = m.group(1).strip("'\"")
            if raw.startswith("data:"):
                return m.group(0)
            local = self._resolve(raw)
            return f"url('{local}')" if local else m.group(0)
        return re.sub(r'url\(\s*([^)]+)\s*\)', _rep, style)
